#!/bin/bash

# This is not always installed by default
command -v mountpoint 2>&1 || \
    { printf '%s\n' "Error: The mountpoint program is not in PATH"; exit 1; }
command -v sshfs 2>&1 || \
    { printf '%s\n' "Error: The sshfs program is not in PATH"; exit 1; }

machine_name="${1:-zybo}"
user="debian"
mountpoint="${HOME}/sshfs/${machine_name}"

mkdir -pv "${mountpoint}"

if mountpoint -q "${mountpoint}"; then
    printf '%s\n' "Error: Something already mounted at ${mountpoint}" >&2
    exit 1
fi

if ! sshfs "${machine_name}:/home/${user}" "${mountpoint}"; then
    printf '%s\n' "Error: Could not mount machine \`${machine_name}\`" >&2
    exit 1
fi

